### ISSUE TITLE
New endpoint request

### ISSUE THREAD

**Issue by zapobyte** [baahrens/goodreads-api-node#1]
Hi,

I'm currently trying to access a endpoint that is not define in your module. The current one that i'm trying to  access is '/book/show/'(https://www.goodreads.com/book/show/50.xml?key=...) . 
This would give access to single book search which has some advantages one of them would be the language_code node for book. 

Can you please add it or can i try and add it ?

Best Regards,
zapo

**Comment by baahrens** [comment]
Yea, sure. Thanks for letting me now. Will have a look later this day/tomorrow and add it ASAP.

**Comment by baahrens** [comment]
Added the basic endpoint yesterday. Please update to 0.0.5 and use the `showBook` function. :+1:
