### ISSUE TITLE
Not able to call showBook api

### ISSUE THREAD

**Issue by sgkhode** [baahrens/goodreads-api-node#11]
I am trying to use showBook API but it is returning nothing.
The issue is the URL returned by getRequestToken is invalid.
This is my code to getRequestToken.
`const goodreads = require('goodreads-api-node');
const gr = goodreads(config.get('goodReads'), "https:\\\\www.wordsmaya.com");
gr.getRequestToken()
.then(url => {  
    console.log(url);
});
`

And ourput printed is
`https://goodreads.com/oauth/authorize?oauth_token=nVu0YBF8O51N2JWhC7n5w&oauth_callback=oob`

How to get this working? My ultimate goal is to get a book details using isbn.

**Comment by baahrens** [comment]
Hey,

Whats wrong with that URL? You have to redirect your user to that URL, so he can provide you access and after that you should be able to call the `getAccessToken()` method. Do you get any error when redirecting your user to the URL?

**Comment by baahrens** [comment]
I'll close this for now. If you still have problems, just open a new issue.
