### ISSUE TITLE
getCurrentUserInfo seems to be missing from the latest release

### ISSUE THREAD

**Issue by onemanwenttomow** [baahrens/goodreads-api-node#15]
any chance of getting it added back in?

`/**
 * getCurrentUserInfo
 *
 * @access public
 * @returns {promise}
 */
function getCurrentUserInfo() {
  var fn_name = 'getCurrentUserInfo()';
   if (!OAUTHENTICATED) return Promise.reject(noOAuthError(fn_name));
   var path = URL + '/api/auth_user';
  var authOptions = _getAuthOptions();
   var req = Request.builder().withPath(path).withOAuth(authOptions).build();
   return _execute(oAuthGet, req);
};
`

**Comment by iambenzo** [comment]
Looking at the code...it looks like it's been renamed to `getUserInfo()`

**Comment by onemanwenttomow** [comment]
Thanks for taking the time to reply. 

I think that is a different one. getUserInfo requires the user id (to get more info on that user). The method i need is the one that gets the users id after they have verified the app. 

getCurrentUserInfo() doesn't require any id.

**Comment by baahrens** [comment]
Sorry for that guys, somehow that function got lost while merging. I readded it and published a new version (`0.0.10`).

Thanks for your patience
