### ISSUE TITLE
Is it possible to add notes to a book with this library?

### ISSUE THREAD

**Issue by RayBB** [baahrens/goodreads-api-node#19]
Thanks for making this great library!

Is it possible to add notes to a book on a bookshelf? It seems like it would be part of addBooksToShelf but I don't see anything related to the notes.

Attached is a screenshot example of what the notes look like on the website.

<img width="811" alt="image" src="https://user-images.githubusercontent.com/921217/72942452-7a2a9100-3d41-11ea-8aff-2eb8c712b809.png">

Thanks!

**Comment by baahrens** [comment]
Hi Ray,

It's still not possible to add notes using the API. See:
https://www.goodreads.com/topic/show/17895540-adding-editing-private-notes-to-users-books-via-api for reference.
Generally the API is pretty much unmaintained, so I don't have hopes that they will add the feature in the future. Sorry.
