### ISSUE TITLE
seriesWorkIsIn is undefined

### ISSUE THREAD

**Issue by smuibrig** [baahrens/goodreads-api-node#26]
Hello,

The latest published version of your package isn't working because of a regression introduced in https://github.com/baahrens/goodreads-api-node/commit/71f48f5c30957fbb628ddb8e749118150c982f67, where `seriesWorkIsIn` got renamed to `getSeriesByWork`, but not all references to it were properly updated.

Thank you for this project!

**Comment by baahrens** [comment]
Hi smuibrig,

Well, that's embarrassing, thanks for the hint. Should be fixed in 0.0.12. 🔮
