### ISSUE TITLE
Basic functionality

### ISSUE THREAD

**Issue by borjadotai** [baahrens/goodreads-api-node#8]
Hi there! 
Great idea to create an API wrapper for goodreads! 
Just wanted to ask, maybe I've missed it, but the wrapper doesn't seem to have a search books functionality does it...? If I want to search book by title or by ISBN for example... It doesn't allow to do something like that does it?

**Comment by borjadotai** [comment]
Also, any idea why it might be giving CORS conflicts when running it from localhost?

**Comment by baahrens** [comment]
Hi,

you can use `searchBooks` to search for a title or author (also `searchAuthors` does exist for this purpose). Searching by ISBN isn't possible at this point of time, though you can get a book by it's goodreads ID with the `showBook` method.

Not sure about the CORS error, this should not happen when querying the goodreads API. Could you show me a screenshot or some code?

**Comment by P3rzival** [comment]
Oh, I see! Great then! Why don't you add it to the readme so people can know that it actually is an included functionality? That might be making some people pass on using it when they shouldn't! 💪

About the CORS error, I'm getting this:

`Failed to load https://goodreads.com/author/list/175417?format=xml&key=N7LgE9pqjTbw7MQboDSTA: Redirect from 'https://goodreads.com/author/list/175417?format=xml&key=N7LgE9pqjTbw7MQboDSTA' to 'https://www.goodreads.com/author/list/175417?format=xml&key=N7LgE9pqjTbw7MQboDSTA' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
search:1 Uncaught (in promise) TypeError: Failed to fetch`

I don't really know much about CORS but from what I'm reading I assume that it has to do with the fact that I'm making the request from localhost and the API doesn't allow that kind of request from localhost?

Newbie over here, so if I'm missing something obvious let me know please, always willing to learn! 😅

**Comment by P3rzival** [comment]
Hey there!
Since you didn't answer, I tried creating a brand new create-react-app and literally copying and pasting the code you have in the usage, still getting this error:

`Failed to load https://goodreads.com/author/list/175417?format=xml&key=N7LgE9pqjTbw7MQboDSTA: Redirect from 'https://goodreads.com/author/list/175417?format=xml&key=N7LgE9pqjTbw7MQboDSTA' to 'https://www.goodreads.com/author/list/175417?format=xml&key=N7LgE9pqjTbw7MQboDSTA' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/:1 Uncaught (in promise) TypeError: Failed to fetch`

**Comment by baahrens** [comment]
Sorry for not answering m8 :disappointed: 
Let me investigate the CORS issue on the weekend. Have to admit that I never really tried this lib in the browser, so I'm not sure, how this behaves with things like cors.

**Comment by borjadotai** [comment]
Yo, @baahrens no worries! 

I closed it cause I saw you were busy and I found out that it's a simple as installing an extension that will set `Allow-Control-Allow-Origin: *` on every request from your browser. 

That way, any error coming from any npm module about CORS gets sorted 😉

Thank anyway man!

Btw, have you had any experience using Amazon's API?

**Comment by baahrens** [comment]
That probably works for developing things, but is by no means a solution to the problem. So I'll have a look at this none the less. Disabling CORS should not be required for this lib to properly work. :grin: 

Not really, no. I've used a few of their services (S3, CloudFront etc) but not their product API or something like that.

**Comment by borjadotai** [comment]
But that's the thing. This problem only seems to occur for developing things when you're making the request from localhost!

Anyway, let me know what you find out 😉
